spring.application.name=DockerL
server.port=9090

# H2 Database Configurations
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=docker
spring.datasource.password=docker

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable H2 Web Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

